SDCB-9992-Appium-2.0-support-for-C#-sample
bitbar/test-samples pull request #505
Opened 2023-08-16 08:12 UTC by MaciejLendzion-smartbear

- Added vendor prefixes to capabilities 
- Added `"bitbar_appiumVersion", "2.0"` capability to run appium 2.0 as default

2023-08-16 09:47 UTC, jczop requested changes
in all examples where platformName is ued it should be without prefix

2023-08-16 09:47 UTC, jczop commented on samples/testing-frameworks/appium/client-side/csharp/biometric-sample-test/BitbarBiometricSample/TestBiometricsAndroid.cs
> +            capabilities.AddAdditionalCapability("appium:platformName", "Android");
according to https://appium.io/docs/en/2.0/guides/caps/
platformName should be without prefix

2023-08-16 09:47 UTC, jczop commented on samples/testing-frameworks/appium/client-side/csharp/biometric-sample-test/BitbarBiometricSample/TestBiometricsIOS.cs
> +            capabilities.AddAdditionalCapability("appium:platformName", "iOS");
according to https://appium.io/docs/en/2.0/guides/caps/
platformName should be without prefix

2023-08-16 09:47 UTC, jczop commented on samples/testing-frameworks/appium/client-side/csharp/sample-test/Test123/Tests.cs
> +			capabilities.AddAdditionalCapability("appium:platformName", "Android");
according to https://appium.io/docs/en/2.0/guides/caps/
platformName should be without prefix

2023-08-17 07:33 UTC, jczop approved these changes

2023-08-17 14:59 UTC, eryk-tkaczewski submitted a review, later dismissed

2023-08-23 13:58 UTC, michal-przytarski commented on samples/testing-frameworks/appium/client-side/csharp/sample-test/Test123/Tests.cs
> +				{"app", "<APP ID>"},
what about extracting `<APP ID>`  to a variable? Same way as `BITBAR_APIKEY`

2023-08-23 13:58 UTC, michal-przytarski commented on samples/testing-frameworks/appium/client-side/csharp/biometric-sample-test/BitbarBiometricSample/TestBiometricsAndroid.cs
> +            capabilities.AddAdditionalCapability("bitbar:options", new Dictionary<string, object>
why not `new Dictionary<string, string>`?

2023-08-24 08:20 UTC, michal-przytarski approved these changes

2023-08-24 08:20 UTC, merged